# Generated by Django 5.2.1 on 2026-02-09 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("TIKTOK", "TikTok"),
                            ("INSTAGRAM", "Instagram"),
                            ("YOUTUBE", "YouTube"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("original_url", models.URLField(max_length=2000)),
                (
                    "normalized_url",
                    models.URLField(
                        help_text="Cleaned URL for tracking.", max_length=2000
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the content was posted on the platform.",
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REMOVED", "Removed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="campaigns.creator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("views", models.BigIntegerField(default=0)),
                ("likes", models.BigIntegerField(default=0)),
                ("comments", models.BigIntegerField(default=0)),
                ("shares", models.BigIntegerField(default=0)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
    ]
