# Generated by Django 5.2.1 on 2026-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("REMOVED", "Removed"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
