# Generated by Django 5.2.11 on 2026-02-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(blank=True, help_text='Title or caption of the content', max_length=255),
        ),
    ]
