# Generated by Django 5.2.1 on 2026-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="budget_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount already paid out",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="budget_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total budget for the campaign",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="campaignmembership",
            name="application_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Answers to application questions"
            ),
        ),
        migrations.AlterField(
            model_name="campaignmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending (Waitlist)"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("BANNED", "Banned"),
                    ("LEFT", "Left"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
