# Generated by Django 5.2.11 on 2026-02-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_image'),
    ]

    operations = [
        # Column already dropped
    ]
