# Generated by Django 5.2.11 on 2026-02-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_zombie_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cpm',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Cost per 1000 views', max_digits=10),
        ),
    ]
