# Generated by Django 5.2.1 on 2026-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectedaccount",
            name="verification_code",
            field=models.CharField(
                blank=True,
                help_text="Code to put in bio for verification",
                max_length=10,
                null=True,
            ),
        ),
    ]
