# Generated by Django 5.2.11 on 2026-02-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_zombie_column'),
        ('integrations', '0002_connectedaccount_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign this account is linked to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_accounts', to='campaigns.campaign'),
        ),
    ]
