# Generated by Django 5.2.11 on 2026-02-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_connectedaccount_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='access_token',
            field=models.TextField(blank=True, help_text='OAuth access token for API access', null=True),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='OAuth refresh token', null=True),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
