# Generated by Django 4.2.28 on 2026-02-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_connectedaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='latest_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
